# Generated by Django 2.1.15 on 2023-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_emp_id_emp_emp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
